_wandb:
    value:
        cli_version: 0.23.0
        e:
            83hpui2ffjjh96bmvmcdkatgjbpo8xbj:
                apple:
                    ecpuCores: 6
                    gpuCores: 18
                    memoryGb: 36
                    name: Apple M3 Pro
                    pcpuCores: 6
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "2147483648"
                codePath: /Users/vadimzenin/ДЗшки/DL/homeworks/hw5/5_Hw_Students.ipynb
                codePathLocal: 5_Hw_Students.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "488479256576"
                email: vazenin@edu.hse.ru
                executable: /usr/local/bin/python3.13
                host: MacBook-Pro-Vadim-3.local
                memory:
                    total: "38654705664"
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/vadimzenin/ДЗшки/DL/homeworks/hw5/5_Hw_Students.ipynb
                python: CPython 3.13.0
                root: /Users/vadimzenin/ДЗшки/DL/homeworks/hw5
                startedAt: "2025-12-20T14:01:33.472096Z"
                writerId: 83hpui2ffjjh96bmvmcdkatgjbpo8xbj
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.0
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": darwin-arm64
architecture:
    value: ResNet50-Pretrained
batch_size:
    value: 64
dataset:
    value: CelebA
epochs:
    value: 15
freeze_backbone:
    value: true
learning_rate:
    value: 0.001
